aws-ec2-testing-scripts/README.md
aws-ec2-testing-scripts/cf-template.json
aws-ec2-testing-scripts/notify.sh
aws-ec2-testing-scripts/run-eval-tests.sh
aws-ec2-testing-scripts/run-high-memory-tests.sh

Scripts that I used during the latest OpenNLP build tests on EC2.

OPENNLP-1111: Adding initial EC2 scripts for testing.

---

aws-ec2-testing-scripts/README.md
aws-ec2-testing-scripts/build-ami.sh
aws-ec2-testing-scripts/cf-template.json
aws-ec2-testing-scripts/notify.sh
aws-ec2-testing-scripts/packer.json
aws-ec2-testing-scripts/run-eval-tests.sh
aws-ec2-testing-scripts/run-high-memory-tests.sh

Contains a Packer script to create an OpenNLP testing AMI and a CloudFormation template to launch the image and run tests.

OPENNLP-1111: Making tests on EC2 automated.

---

tf-ner-poc/src/main/python/namefinder.py

added vector size to NameFinder + only save model if improved + stop training if not improved for 5 iteration

various minor changes

---

opennlp-dl/pom.xml
opennlp-dl/src/main/java/opennlp/tools/dl/DataReader.java
opennlp-dl/src/main/java/opennlp/tools/dl/NameFinderDL.java
opennlp-dl/src/main/java/opennlp/tools/dl/NameSampleDataSetIterator.java
opennlp-dl/src/main/java/opennlp/tools/dl/NeuralDocCat.java
opennlp-dl/src/main/java/opennlp/tools/dl/NeuralDocCatTrainer.java
opennlp-dl/src/main/java/opennlp/tools/dl/RNN.java
opennlp-dl/src/main/java/opennlp/tools/dl/StackedRNN.java
opennlp-dl/src/test/java/opennlp/tools/dl/StackedRNNTest.java

simple patch for dl4j version upgrade

OPENNLP-1009 - upgrade to dl4j 1.0.0-beta2

---

tf-ner-poc/src/main/python/namefinder/namefinder.py

Just fixing some visual warnings and a None comparison.

TF_NER_POC: Fix PEP 8 python style warnings

---

tf-ner-poc/src/main/python/namefinder/namefinder.py

Add UNK vector if word isn't in the embedding vector

TF_NER_POC: Fix missing UNK vector

---

tf-ner-poc/src/main/python/namefinder/namefinder.py

TF_NER_POC: Improve encode labels

---

opennlp-coref/pom.xml
opennlp-coref/src/main/java/opennlp/tools/cmdline/coref/CoreferencerTool.java
opennlp-coref/src/main/java/opennlp/tools/coref/resolver/AbstractResolver.java
opennlp-coref/src/main/java/opennlp/tools/coref/resolver/DefaultNonReferentialResolver.java
opennlp-coref/src/main/java/opennlp/tools/coref/resolver/MaxentResolver.java
opennlp-coref/src/main/java/opennlp/tools/coref/sim/GenderModel.java
opennlp-coref/src/main/java/opennlp/tools/coref/sim/NumberModel.java
opennlp-coref/src/main/java/opennlp/tools/coref/sim/SimilarityModel.java
opennlp-coref/src/main/java/opennlp/tools/formats/CorefSampleStreamFactory.java

- adjusts `opennlp-tools` to 2.1.0
- adjusts parent project (org.apache.apache) to version `18`
- adjusts Java language level to 11

Update sandbox component 'opennlp-coref' to be compatible with latest opennlp-tools release

---

caseditor-opennlp-plugin/pom.xml
caseditor-opennlp-plugin/src/main/java/org/apache/opennlp/caseditor/ConfirmAnnotationAction.java
caseditor-opennlp-plugin/src/main/java/org/apache/opennlp/caseditor/OpenNLPPreferenceInitializer.java
caseditor-opennlp-plugin/src/main/java/org/apache/opennlp/caseditor/OpenNLPPreferencePage.java
caseditor-opennlp-plugin/src/main/java/org/apache/opennlp/caseditor/OpenPreferenceDialog.java
caseditor-opennlp-plugin/src/main/java/org/apache/opennlp/caseditor/PotentialAnnotation.java
caseditor-opennlp-plugin/src/main/java/org/apache/opennlp/caseditor/PotentialAnnotationComparator.java
caseditor-opennlp-plugin/src/main/java/org/apache/opennlp/caseditor/TypeFieldEditor.java
caseditor-opennlp-plugin/src/main/java/org/apache/opennlp/caseditor/TypeInputDialog.java
caseditor-opennlp-plugin/src/main/java/org/apache/opennlp/caseditor/TypeListFieldEditor.java
caseditor-opennlp-plugin/src/main/java/org/apache/opennlp/caseditor/namefinder/ConfirmedNameDetectionFieldEditor.java
caseditor-opennlp-plugin/src/main/java/org/apache/opennlp/caseditor/namefinder/EntityContentProvider.java
caseditor-opennlp-plugin/src/main/java/org/apache/opennlp/caseditor/namefinder/MultiModelNameFinder.java
caseditor-opennlp-plugin/src/main/java/org/apache/opennlp/caseditor/namefinder/NameFinderJob.java
caseditor-opennlp-plugin/src/main/java/org/apache/opennlp/caseditor/namefinder/NameFinderModelFieldEditor.java
caseditor-opennlp-plugin/src/main/java/org/apache/opennlp/caseditor/namefinder/NameFinderModelInputDialog.java
caseditor-opennlp-plugin/src/main/java/org/apache/opennlp/caseditor/namefinder/NameFinderPreferencePage.java
caseditor-opennlp-plugin/src/main/java/org/apache/opennlp/caseditor/namefinder/NameFinderViewPage.java
caseditor-opennlp-plugin/src/main/java/org/apache/opennlp/caseditor/namefinder/PotentialEntityAnnotationLabelProvider.java
caseditor-opennlp-plugin/src/main/java/org/apache/opennlp/caseditor/sentdetect/SentenceContentProvider.java
caseditor-opennlp-plugin/src/main/java/org/apache/opennlp/caseditor/sentdetect/SentenceDetectorJob.java
caseditor-opennlp-plugin/src/main/java/org/apache/opennlp/caseditor/sentdetect/SentenceDetectorPreferencePage.java
caseditor-opennlp-plugin/src/main/java/org/apache/opennlp/caseditor/sentdetect/SentenceDetectorViewPage.java
caseditor-opennlp-plugin/src/main/java/org/apache/opennlp/caseditor/sentdetect/SentenceLabelProvider.java
caseditor-opennlp-plugin/src/main/java/org/apache/opennlp/caseditor/tokenize/TokenizerJob.java
caseditor-opennlp-plugin/src/main/java/org/apache/opennlp/caseditor/tokenize/TokenizerPreferencePage.java
caseditor-opennlp-plugin/src/main/java/org/apache/opennlp/caseditor/tokenize/TokenizerView.java
caseditor-opennlp-plugin/src/main/java/org/apache/opennlp/caseditor/tokenize/TokenizerViewPage.java
caseditor-opennlp-plugin/src/main/java/org/apache/opennlp/caseditor/util/ContainingConstraint.java
caseditor-opennlp-plugin/src/main/java/org/apache/opennlp/caseditor/util/UIMAUtil.java

- adjusts opennlp-tools to 2.1.0
- adjusts parent project (org.apache.apache) to version 18
- adjusts Java language level to 11
- updates `uimaj` dependencies to version 2.10.4
- updates `maven-bundle-plugin` to version 5.1.8 so things work with class files compiled in Java 11 format
- adjusts some array declarations to comply with Java, not C style
- removes unused imports

Update sandbox component 'caseditor-opennlp-plugin' to be compatible with latest opennlp-tools release

---

opennlp-wsd/src/main/java/opennlp/tools/disambiguator/datareader/Paragraph.java

Fix for [OPENNLP-985](https://issues.apache.org/jira/browse/OPENNLP-985).

OPENNLP-985: fix an if statement that always returned true.

---

opennlp-similarity/pom.xml
opennlp-similarity/src/main/java/opennlp/tools/apps/review_builder/FBOpenGraphSearchManager.java
opennlp-similarity/src/main/java/opennlp/tools/apps/review_builder/MachineTranslationWrapper.java
opennlp-similarity/src/main/java/opennlp/tools/apps/review_builder/MinedSentenceProcessor.java
opennlp-similarity/src/main/java/opennlp/tools/apps/review_builder/ParserConstants.java
opennlp-similarity/src/main/java/opennlp/tools/apps/review_builder/ReviewBuilderRunner.java
opennlp-similarity/src/main/java/opennlp/tools/apps/review_builder/ReviewObj.java
opennlp-similarity/src/main/java/opennlp/tools/apps/review_builder/SentenceBeingOriginalized.java
opennlp-similarity/src/main/java/opennlp/tools/apps/review_builder/SentenceOriginalizer.java
opennlp-similarity/src/main/java/opennlp/tools/apps/review_builder/URLsWithReviewFinderByProductName.java
opennlp-similarity/src/main/java/opennlp/tools/apps/review_builder/WebPageReviewExtractor.java

- updates several 3rd party dependencies to more recent, conflict free versions
- adds missing license headers in `review_builder` package

Modernize dependencies of opennlp-similarity component

---

nlp-utils/src/main/java/org/apache/opennlp/utils/anomalydetection/AnomalyDetectionUtils.java
nlp-utils/src/main/java/org/apache/opennlp/utils/regression/GradientDescentUtils.java
nlp-utils/src/test/java/org/apache/opennlp/utils/regression/GradientDescentUtilsTest.java

Change
-
- adjusts parameter alpha in GradientDescentUtilsTest from `0.00002` to `0.00001`
- aforementioned param change results in stable convergence, checked via RepeatedTest (JUnit)
- optimizes how random values are obtained in `GradientDescentUtils`
- fixes a potentially unpredictable BigDecimal value in `AnomalyDetectionUtils` (see JavaDoc of that constructor)
Tasks
-

OPENNLP-1472 Fix flaky (sub-) test of GradientDescentUtilsTest in sandbox component 'nlp-utils'

---

opennlp-similarity/src/main/java/opennlp/tools/similarity/apps/utils/ValueSortMap.java
opennlp-similarity/src/test/java/opennlp/tools/similarity/apps/utils/ValueSortMapTest.java

Change
-
- clears 'raw use of parameterized' problems in `ValueSortMap`
- adds `ValueSortMapTest` by converting a main method test approach to actual unit test(s)
- improves JavaDoc
Tasks
-

Remove raw use of parameterized in ValueSortMap and provide unit test

---

pom.xml

Change
-
- upgrades the `forbiddenapis` Maven plugin to the lastest version which adds support for checks on newer JDK versions
- adds extra forbiddenapis bundles/checks to the config to be more strict (=> passes)
- removes incorrect excludes (patterns) in `maven-surefire-plugin` sandbox config
Tasks
-

Update build dependency forbiddenapis to version 3.4

---

mallet-addon/src/main/java/opennlp/addons/mallet/CRFTrainer.java
mallet-addon/src/main/java/opennlp/addons/mallet/TransducerModel.java
mallet-addon/src/main/java/opennlp/addons/mallet/TransducerModelSerializer.java
opennlp-coref/src/main/java/opennlp/tools/cmdline/coref/CoreferenceConverterTool.java
opennlp-coref/src/main/java/opennlp/tools/formats/CorefSampleStreamFactory.java
opennlp-coref/src/main/java/opennlp/tools/formats/muc/Muc6FullParseCorefSampleStreamFactory.java
pom.xml

Update sandbox components to use opennlp-tools version 2.1.1

---

caseditor-corpus-server-plugin/pom.xml
caseditor-opennlp-plugin/pom.xml
corpus-server/corpus-server-connector/pom.xml
corpus-server/corpus-server-core/pom.xml
corpus-server/corpus-server-impl/pom.xml
corpus-server/corpus-server-tools/pom.xml
mahout-addon/pom.xml
mahout-addon/src/main/java/opennlp/addons/mahout/AbstractOnlineLearnerTrainer.java
modelbuilder-addon/pom.xml
nlp-utils/pom.xml
opennlp-dl/pom.xml
opennlp-similarity/pom.xml
opennlp-wsd/pom.xml
pom.xml
summarizer/pom.xml
tagging-server/feature.xml
tagging-server/pom.xml
tf-ner-poc/pom.xml
wikinews-importer/pom.xml

Change
-
- optimizes dependency management / organization in sandbox modules
- updates outdated OpenNLP version strings so latest 2.1.1 is used from parent pom
- adapts `AbstractOnlineLearnerTrainer` due to minor API change
- updates junit-jupiter to version 5.9.2
Tasks
-

Optimize organization of managed dependencies in pom files

---

caseditor-corpus-server-plugin/pom.xml
caseditor-corpus-server-plugin/src/main/java/org/apache/opennlp/corpus_server/caseditor/DefaultCasDocumentProvider.java
caseditor-corpus-server-plugin/src/main/java/org/apache/opennlp/corpus_server/caseditor/SearchCorpusServerJob.java
caseditor-corpus-server-plugin/src/main/java/org/apache/opennlp/corpus_server/caseditor/TaskQueueView.java
corpus-server/corpus-server-connector/pom.xml
corpus-server/corpus-server-connector/src/main/java/org/apache/opennlp/corpus_server/connector/CSCasWriter.java
corpus-server/corpus-server-connector/src/main/java/org/apache/opennlp/corpus_server/connector/CSQueueCollectionReader.java
corpus-server/corpus-server-connector/src/main/java/org/apache/opennlp/corpus_server/connector/UimaUtil.java
corpus-server/corpus-server-core/feature.xml
corpus-server/corpus-server-core/pom.xml
corpus-server/corpus-server-core/src/main/java/org/apache/opennlp/corpus_server/CorpusServerBundle.java
corpus-server/corpus-server-impl/pom.xml
corpus-server/corpus-server-tools/pom.xml
corpus-server/corpus-server-tools/src/main/java/org/apache/opennlp/corpus_server/tools/CASImporter.java
corpus-server/corpus-server-tools/src/main/java/org/apache/opennlp/corpus_server/tools/CorpusBackup.java
corpus-server/corpus-server-tools/src/main/java/org/apache/opennlp/corpus_server/tools/CreateCorpus.java
corpus-server/corpus-server-tools/src/main/java/org/apache/opennlp/corpus_server/tools/CreateTaskQueue.java
corpus-server/corpus-server-tools/src/main/java/org/apache/opennlp/corpus_server/tools/DropCorpus.java
corpus-server/corpus-server-tools/src/main/java/org/apache/opennlp/corpus_server/tools/FileUtil.java
corpus-server/corpus-server-tools/src/main/java/org/apache/opennlp/corpus_server/tools/RemoveCAS.java
corpus-server/corpus-server-tools/src/main/java/org/apache/opennlp/corpus_server/tools/ReplaceTypeSystem.java
corpus-server/corpus-server-tools/src/main/java/org/apache/opennlp/corpus_server/tools/SearchCorpus.java
corpus-server/pom.xml
mahout-addon/pom.xml
pom.xml
tagging-server/feature.xml
tagging-server/pom.xml
tagging-server/src/main/java/org/apache/opennlp/tagging_server/TaggingServerBundle.java
wikinews-importer/pom.xml

Change 
-
Modernizes several components to rely on a more recent version of Jersey 2.x instead of ancient 1.x versions. The components are:
- tagging-server
- corpus-server and its components
- caseditor-corpus-server-plugin
- wikinews-importer (Jersey never used/required here)
Migration guides used:
- https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/migration.html#mig-1.x
- https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/migration.html#mig-client-api
Tasks
-
Please ensure that once the PR is submitted, you check GitHub Actions for build issues and submit an update to …

Modernize sandbox components towards a more recent version of Jersey 2.x

---

summarizer/src/main/java/opennlp/summarization/Score.java
summarizer/src/main/java/opennlp/summarization/Sentence.java
summarizer/src/main/java/opennlp/summarization/lexicalchaining/WordRelationshipDetermination.java
summarizer/src/main/java/opennlp/summarization/preprocess/DefaultDocProcessor.java
summarizer/src/main/java/opennlp/summarization/textrank/TextRank.java

Change
-
- enhances existing code in the `summarizer` component to use "\\s+" as split pattern instead of simply using a regular whitespace (" ").
- improves JavaDoc along the path
- improves formatting along the path

Enhance split by whitespace operations to cover more cases (summarizer)

---

pom.xml

OPENNLP-1491 Update build dependency javadoc plugin to version 3.5.0 (sandbox)

---

caseditor-corpus-server-plugin/pom.xml
caseditor-opennlp-plugin/pom.xml
corpus-server/corpus-server-connector/pom.xml
corpus-server/corpus-server-core/feature.xml
corpus-server/corpus-server-core/pom.xml
corpus-server/corpus-server-impl/feature.xml
corpus-server/corpus-server-impl/pom.xml
corpus-server/corpus-server-tools/pom.xml
corpus-server/pom.xml
mahout-addon/pom.xml
mallet-addon/pom.xml
modelbuilder-addon/pom.xml
nlp-utils/pom.xml
opennlp-coref/pom.xml
opennlp-dl/pom.xml
opennlp-similarity/pom.xml
opennlp-wsd/pom.xml
pom.xml
summarizer/pom.xml
tagging-server/feature.xml
tagging-server/pom.xml
tf-ner-poc/pom.xml
wikinews-importer/pom.xml

Change
-
- updates sandbox components to use opennlp-tools version 2.2.0
- bumps version of sandbox components to 2.2.1-SNAPSHOT
Tasks
-

Update sandbox components to use opennlp-tools version 2.2.0

---

.asf.yml

- Updates the titles of the auto generated messages from GitHub like described in https://community.apache.org/contributors/mailing-lists.html#configuring-the-subject-lines-of-the-emails-being-sent
- Make it human readable like in https://lists.apache.org/list?dev@streampipes.apache.org:lte=4M 
- Prevent force pushed on master / main.

OPENNLP-1503 -  Configure auto generated subject lines in mail templates from GH

---

.github/workflows/maven.yml
caseditor-corpus-server-plugin/pom.xml
caseditor-opennlp-plugin/pom.xml
corpus-server/corpus-server-connector/pom.xml
corpus-server/corpus-server-core/feature.xml
corpus-server/corpus-server-core/pom.xml
corpus-server/corpus-server-impl/feature.xml
corpus-server/corpus-server-impl/pom.xml
corpus-server/corpus-server-tools/pom.xml
corpus-server/pom.xml
mahout-addon/pom.xml
mallet-addon/pom.xml
modelbuilder-addon/pom.xml
nlp-utils/pom.xml
opennlp-coref/pom.xml
opennlp-dl/pom.xml
opennlp-similarity/pom.xml
opennlp-wsd/pom.xml
pom.xml
summarizer/pom.xml
tagging-server/feature.xml
tagging-server/pom.xml
tf-ner-poc/pom.xml
wikinews-importer/pom.xml

Change
-
- updates sandbox components to use `opennlp-tools` version `2.3.0`
- aligns uimaj dep version with version in core project (3.4.1)
Tasks
-

OpenNLP-1496 Migrate opennlp-sandbox to Java 17 LTS

---

.github/workflows/maven.yml

Change
-
- adds JDK 21 to CI config
- removes EOL JDK 19 from CI config
Tasks
-

Add LTS JDK version 21 to GH actions config

---

caseditor-corpus-server-plugin/pom.xml
caseditor-opennlp-plugin/pom.xml
corpus-server/corpus-server-connector/pom.xml
corpus-server/corpus-server-core/feature.xml
corpus-server/corpus-server-core/pom.xml
corpus-server/corpus-server-impl/feature.xml
corpus-server/corpus-server-impl/pom.xml
corpus-server/corpus-server-tools/pom.xml
corpus-server/pom.xml
mahout-addon/pom.xml
mallet-addon/pom.xml
modelbuilder-addon/pom.xml
nlp-utils/pom.xml
opennlp-coref/pom.xml
opennlp-coref/src/main/java/opennlp/tools/lang/english/TreebankNameFinder.java
opennlp-dl/pom.xml
opennlp-similarity/pom.xml
opennlp-wsd/pom.xml
pom.xml
summarizer/pom.xml
tagging-server/feature.xml
tagging-server/pom.xml
tf-ner-poc/pom.xml
wikinews-importer/pom.xml

Change
-
- updates sandbox components to use opennlp-tools version 2.3.1
- bumps version of sandbox components to 2.3.2-SNAPSHOT
Tasks
-

Update sandbox components to use opennlp-tools version 2.3.1

---

caseditor-corpus-server-plugin/pom.xml
caseditor-opennlp-plugin/pom.xml
corpus-server/corpus-server-connector/pom.xml
corpus-server/corpus-server-core/feature.xml
corpus-server/corpus-server-core/pom.xml
corpus-server/corpus-server-impl/feature.xml
corpus-server/corpus-server-impl/pom.xml
corpus-server/corpus-server-tools/pom.xml
corpus-server/pom.xml
mahout-addon/pom.xml
mallet-addon/pom.xml
modelbuilder-addon/pom.xml
nlp-utils/pom.xml
opennlp-coref/pom.xml
opennlp-dl/pom.xml
opennlp-similarity/pom.xml
opennlp-wsd/pom.xml
pom.xml
summarizer/pom.xml
tagging-server/feature.xml
tagging-server/pom.xml
tf-ner-poc/pom.xml
wikinews-importer/pom.xml

Change
-
-updates sandbox components to use `opennlp-tools` version `2.3.3`
-bumps version of sandbox components to `2.3.4-SNAPSHOT`
Tasks
-

Update sandbox components to use opennlp-tools version 2.3.3

---

mallet-addon/src/main/java/opennlp/addons/mallet/CRFTrainer.java
mallet-addon/src/main/java/opennlp/addons/mallet/TransducerModel.java
mallet-addon/src/main/java/opennlp/addons/mallet/TransducerModelSerializer.java
opennlp-similarity/pom.xml
opennlp-similarity/src/main/java/opennlp/tools/similarity/apps/solr/IterativeSearchRequestHandler.java
opennlp-wsd/pom.xml
opennlp-wsd/src/main/java/opennlp/tools/disambiguator/WSDEvaluator.java
opennlp-wsd/src/main/java/opennlp/tools/disambiguator/WSDHelper.java
pom.xml
wikinews-importer/src/main/java/org/apache/opennlp/wikinews_importer/AnnotatingMarkupParser.java

Align sandbox components with latest opennlp tools (snapshot) version

---

summarizer/src/main/java/opennlp/summarization/lexicalchaining/WordRelationshipDetermination.java

Change
-
- speeds up both `MetaSummarizer` and `LexicalChainSummarizer` by optimizing resource initialization in `WordRelationshipDetermination`
- reduces time required for text summarization drastically (cuts test execution time by two thirds)
Tasks
-

OPENNLP-1592 Provide tests for MetaSummarizer - performance improvement

---

summarizer/src/main/java/opennlp/summarization/lexicalchaining/LexicalChainingSummarizer.java
summarizer/src/main/java/opennlp/summarization/meta/MetaSummarizer.java
summarizer/src/main/java/opennlp/summarization/textrank/TextRankSummarizer.java
summarizer/src/test/java/opennlp/summarization/AbstractSummarizerTest.java
summarizer/src/test/java/opennlp/summarization/lexicalchaining/LexicalChainingSummarizerTest.java
summarizer/src/test/java/opennlp/summarization/textrank/TextRankSummarizerTest.java

Change
-
- provides JUnit tests for `LexicalChainingSummarizer` and `TextRankSummarizer`
- improves the existing code so that summarization works, fixes a bug in `LexicalChainingSummarizer#summarize`
- improves the code quality
- adds JavaDoc where possible
Tasks
-

OPENNLP-1593 Provide tests for all Summarizer implementations

---

caseditor-corpus-server-plugin/pom.xml
caseditor-opennlp-plugin/pom.xml
corpus-server/corpus-server-connector/pom.xml
corpus-server/corpus-server-core/pom.xml
corpus-server/corpus-server-impl/pom.xml
corpus-server/corpus-server-tools/pom.xml
corpus-server/pom.xml
mahout-addon/pom.xml
mallet-addon/pom.xml
modelbuilder-addon/pom.xml
nlp-utils/pom.xml
opennlp-coref/pom.xml
opennlp-dl/pom.xml
opennlp-similarity/pom.xml
opennlp-wsd/pom.xml
pom.xml
summarizer/pom.xml
tagging-server/pom.xml
tf-ner-poc/pom.xml
wikinews-importer/pom.xml

Update Sandbox components to use OpenNLP tools version 2.4.0

---

opennlp-coref/src/main/java/opennlp/tools/cmdline/coref/CoreferencerTool.java
opennlp-coref/src/main/java/opennlp/tools/coref/AbstractParse.java
opennlp-coref/src/main/java/opennlp/tools/coref/CorefParse.java
opennlp-coref/src/main/java/opennlp/tools/coref/DiscourseModel.java
opennlp-coref/src/main/java/opennlp/tools/coref/dictionary/DictionaryFactory.java
opennlp-coref/src/main/java/opennlp/tools/coref/dictionary/JWNLDictionary.java
opennlp-coref/src/main/java/opennlp/tools/coref/linker/AbstractLinker.java
opennlp-coref/src/main/java/opennlp/tools/coref/linker/DefaultLinker.java
opennlp-coref/src/main/java/opennlp/tools/coref/mention/AbstractMentionFinder.java
opennlp-coref/src/main/java/opennlp/tools/coref/mention/MentionContext.java
opennlp-coref/src/main/java/opennlp/tools/coref/mention/PTBHeadFinder.java
opennlp-coref/src/main/java/opennlp/tools/coref/mention/ShallowParseMentionFinder.java
opennlp-coref/src/main/java/opennlp/tools/coref/resolver/AbstractResolver.java
opennlp-coref/src/main/java/opennlp/tools/coref/resolver/DefaultNonReferentialResolver.java
opennlp-coref/src/main/java/opennlp/tools/coref/resolver/IsAResolver.java
opennlp-coref/src/main/java/opennlp/tools/coref/resolver/MaxentResolver.java
opennlp-coref/src/main/java/opennlp/tools/coref/resolver/PluralPronounResolver.java
opennlp-coref/src/main/java/opennlp/tools/coref/resolver/ProperNounResolver.java
opennlp-coref/src/main/java/opennlp/tools/coref/resolver/ResolverUtils.java
opennlp-coref/src/main/java/opennlp/tools/coref/resolver/SingularPronounResolver.java
opennlp-coref/src/main/java/opennlp/tools/coref/resolver/SpeechPronounResolver.java
opennlp-coref/src/main/java/opennlp/tools/coref/sim/Context.java
opennlp-coref/src/main/java/opennlp/tools/coref/sim/GenderModel.java
opennlp-coref/src/main/java/opennlp/tools/coref/sim/MaxentCompatibilityModel.java
opennlp-coref/src/main/java/opennlp/tools/coref/sim/NumberModel.java
opennlp-coref/src/main/java/opennlp/tools/coref/sim/SimilarityModel.java
opennlp-coref/src/main/java/opennlp/tools/formats/muc/MucMentionInserterStream.java
opennlp-coref/src/main/java/opennlp/tools/lang/english/TreebankNameFinder.java

What does this PR do? It...
-
- removes all `System.out/err` logging and `e.printStackTrace()` calls from Coref component
- introduces proper (slf4j) logging instead
- adds `@Override` annotation where appropriate
- drops commented / orphaned code
- applies code cosmetics: removing useless brackets
Tasks
-

OPENNLP-1614: Clean plain Sys.out logging from Coref component

---

README.md

OPENNLP-1621: Add a README to the root of the Sandbox projects

---

opennlp-brat-annotator/pom.xml
opennlp-brat-annotator/src/main/bin/brat-annotation-service
opennlp-brat-annotator/src/main/bin/brat-annotation-service.bat
opennlp-brat-annotator/src/main/java/opennlp/bratann/NameFinderAnnService.java
opennlp-brat-annotator/src/main/java/opennlp/bratann/NameFinderResource.java
pom.xml

Draft until discussion reaches consensus: https://lists.apache.org/thread/smjkp8rh4w59cnfd3n3lhc8jj2bzz2zz

OPENNLP-1634 - Move OpenNLP Brat Annotator back to Sandbox

---

caseditor-corpus-server-plugin/pom.xml
caseditor-opennlp-plugin/pom.xml
corpus-server/corpus-server-connector/pom.xml
corpus-server/corpus-server-core/pom.xml
corpus-server/corpus-server-impl/pom.xml
corpus-server/corpus-server-tools/pom.xml
corpus-server/pom.xml
mahout-addon/pom.xml
mallet-addon/pom.xml
modelbuilder-addon/pom.xml
nlp-utils/pom.xml
opennlp-brat-annotator/pom.xml
opennlp-coref/pom.xml
opennlp-dl/pom.xml
opennlp-similarity/pom.xml
opennlp-wsd/pom.xml
pom.xml
summarizer/pom.xml
tagging-server/pom.xml
tf-ner-poc/pom.xml
wikinews-importer/pom.xml

- updates sandbox components to use opennlp-tools version 2.5.0
- bumps version of sandbox components to 2.5.1-SNAPSHOT

Switch to OpenNLP tools 2.5.0

---

opennlp-similarity/pom.xml

Change
-
- cleans dependency management section in opennlp-similarity/pom.xml from orphaned dependency towards **Lombok**
Tasks
-

Cleans dependency management section in opennlp-similarity/pom.xml

---

caseditor-corpus-server-plugin/pom.xml
caseditor-opennlp-plugin/pom.xml
corpus-server/corpus-server-connector/pom.xml
corpus-server/corpus-server-core/pom.xml
corpus-server/corpus-server-impl/pom.xml
corpus-server/corpus-server-tools/pom.xml
corpus-server/pom.xml
mahout-addon/pom.xml
mallet-addon/pom.xml
modelbuilder-addon/pom.xml
nlp-utils/pom.xml
opennlp-brat-annotator/pom.xml
opennlp-coref/pom.xml
opennlp-dl/pom.xml
opennlp-similarity/pom.xml
opennlp-wsd/pom.xml
pom.xml
summarizer/pom.xml
tagging-server/pom.xml
tf-ner-poc/pom.xml
wikinews-importer/pom.xml

Changes
-
- updates sandbox components to use opennlp-tools version 2.5.1
- bumps version of sandbox components to 2.5.2-SNAPSHOT
Tasks
-

Switch to OpenNLP tools 2.5.1

---

opennlp-grpc/README.md
opennlp-grpc/examples/python-client/opennlp_pb2.py
opennlp-grpc/examples/python-client/opennlp_pb2_grpc.py
opennlp-grpc/opennlp-grpc-api/opennlp.md
opennlp-grpc/opennlp-grpc-api/opennlp.proto
opennlp-grpc/opennlp-grpc-api/src/main/java/opennlp/OpenNLPService.java
opennlp-grpc/opennlp-grpc-api/src/main/java/opennlp/SentenceDetectorServiceGrpc.java
opennlp-grpc/opennlp-grpc-api/src/main/java/opennlp/TokenizerTaggerServiceGrpc.java
opennlp-grpc/opennlp-grpc-service/pom.xml
opennlp-grpc/opennlp-grpc-service/src/main/java/opennlp/OpenNLPServer.java
opennlp-grpc/opennlp-grpc-service/src/main/java/opennlp/service/CacheAware.java
opennlp-grpc/opennlp-grpc-service/src/main/java/opennlp/service/ExceptionAware.java
opennlp-grpc/opennlp-grpc-service/src/main/java/opennlp/service/ModelAware.java
opennlp-grpc/opennlp-grpc-service/src/main/java/opennlp/service/ModelFinderUtil.java
opennlp-grpc/opennlp-grpc-service/src/main/java/opennlp/service/PosTaggerService.java
opennlp-grpc/opennlp-grpc-service/src/main/java/opennlp/service/SentenceDetectorService.java
opennlp-grpc/opennlp-grpc-service/src/main/java/opennlp/service/TokenizerService.java
opennlp-grpc/opennlp-grpc-service/src/test/java/opennlp/OpenNLPServerIT.java
opennlp-grpc/opennlp-grpc-service/src/test/java/opennlp/service/AbstractServiceTest.java
opennlp-grpc/opennlp-grpc-service/src/test/java/opennlp/service/PosTaggerServiceTest.java
opennlp-grpc/opennlp-grpc-service/src/test/java/opennlp/service/SentenceDetectorServiceTest.java
opennlp-grpc/opennlp-grpc-service/src/test/java/opennlp/service/TokenizerServiceTest.java
opennlp-grpc/opennlp-grpc-service/src/test/java/opennlp/service/stubs/TestStreamObserver.java
opennlp-grpc/opennlp-grpc-service/src/test/resources/config-test.ini

- Implement TokenizerService and SentenceDetectorService.
- Reduces code duplication for multiple service by using default interface methods
- Adds Unit and Integration Tests
- Regenerate documentation and updates README

OPENNLP-1665 - Implement TokenizerService and SentenceDetectorService

---

opennlp-wsd/pom.xml
opennlp-wsd/src/main/java/opennlp/tools/disambiguator/AbstractWSDisambiguator.java
opennlp-wsd/src/main/java/opennlp/tools/disambiguator/Disambiguator.java
opennlp-wsd/src/main/java/opennlp/tools/disambiguator/FeaturesExtractor.java
opennlp-wsd/src/main/java/opennlp/tools/disambiguator/IMSWSDContextGenerator.java
opennlp-wsd/src/main/java/opennlp/tools/disambiguator/IMSWSDSequenceValidator.java
opennlp-wsd/src/main/java/opennlp/tools/disambiguator/Lesk.java
opennlp-wsd/src/main/java/opennlp/tools/disambiguator/LeskParameters.java
opennlp-wsd/src/main/java/opennlp/tools/disambiguator/MFS.java
opennlp-wsd/src/main/java/opennlp/tools/disambiguator/SynNode.java
opennlp-wsd/src/main/java/opennlp/tools/disambiguator/WSDContextGenerator.java
opennlp-wsd/src/main/java/opennlp/tools/disambiguator/WSDDefaultParameters.java
opennlp-wsd/src/main/java/opennlp/tools/disambiguator/WSDEvaluationMonitor.java
opennlp-wsd/src/main/java/opennlp/tools/disambiguator/WSDEvaluator.java
opennlp-wsd/src/main/java/opennlp/tools/disambiguator/WSDHelper.java
opennlp-wsd/src/main/java/opennlp/tools/disambiguator/WSDModel.java
opennlp-wsd/src/main/java/opennlp/tools/disambiguator/WSDParameters.java
opennlp-wsd/src/main/java/opennlp/tools/disambiguator/WSDSample.java
opennlp-wsd/src/main/java/opennlp/tools/disambiguator/WSDisambiguatorFactory.java
opennlp-wsd/src/main/java/opennlp/tools/disambiguator/WTDIMS.java
opennlp-wsd/src/main/java/opennlp/tools/disambiguator/WordPOS.java
opennlp-wsd/src/main/java/opennlp/tools/disambiguator/WordSense.java

OPENNLP-789: Extend JavaDoc for WSD component

---

.github/workflows/maven.yml
caseditor-corpus-server-plugin/pom.xml
caseditor-opennlp-plugin/pom.xml
corpus-server/corpus-server-connector/pom.xml
corpus-server/corpus-server-core/pom.xml
corpus-server/corpus-server-impl/pom.xml
corpus-server/corpus-server-tools/pom.xml
corpus-server/pom.xml
mahout-addon/pom.xml
mallet-addon/pom.xml
modelbuilder-addon/pom.xml
nlp-utils/pom.xml
opennlp-brat-annotator/pom.xml
opennlp-coref/pom.xml
opennlp-dl/pom.xml
opennlp-grpc/README.md
opennlp-grpc/opennlp-grpc-api/pom.xml
opennlp-grpc/opennlp-grpc-service/pom.xml
opennlp-grpc/opennlp-grpc-service/src/main/java/opennlp/OpenNLPServer.java
opennlp-grpc/pom.xml
opennlp-similarity/pom.xml
opennlp-wsd/pom.xml
pom.xml
summarizer/pom.xml
tagging-server/pom.xml
tf-ner-poc/pom.xml
wikinews-importer/pom.xml

Change
-
- bumps version of sandbox components to 2.5.4-SNAPSHOT
- adjusts GH actions to check experimental Java 24-ea
Tasks
-
- [] Is there a JIRA ticket associated with this PR? Is it referenced 

Update sandbox components to OpenNLP tools 2.5.3

---

.github/workflows/license.yaml
LICENSE
NOTICE
pom.xml
src/license/NOTICE.template
src/license/THIRD-PARTY.properties

- Adds missing LICENSE
- Adds tooling via GH actions to automatically generate NOTICE file from dependencies. If there is a difference in the NOTICE file upon dependency updates, the GH action will create a PR to address this issue.

OPENNLP-1693 - Sandbox Repository is missing LICENSE and NOTICE files

---

.github/dependabot.yml

OPENNLP-1690: Add opennlp-tools to dependabot excludes of addons/sandbox

---

corpus-server/corpus-server-connector/src/test/java/org/apache/opennlp/corpus_server/connector/AbstractCSTest.java
corpus-server/corpus-server-connector/src/test/java/org/apache/opennlp/corpus_server/connector/CSCasWriterTest.java

as the title says - solving the riddle ;-)

Fix failing CSCasWriterTest in Windows environments

---

corpus-server/corpus-server-impl/pom.xml
opennlp-coref/src/test/java/opennlp/tools/coref/AbstractCorefTest.java
opennlp-coref/src/test/java/opennlp/tools/formats/muc/Muc6FullParseCorefSampleStreamFactoryTest.java
opennlp-similarity/pom.xml
opennlp-similarity/src/main/java/opennlp/tools/textsimilarity/chunker2matcher/ParserChunker2MatcherProcessor.java
opennlp-similarity/src/main/java/opennlp/tools/textsimilarity/chunker2matcher/ParserPure2MatcherProcessor.java
opennlp-wsd/pom.xml
opennlp-wsd/src/main/java/opennlp/tools/disambiguator/WSDHelper.java
pom.xml
summarizer/pom.xml
summarizer/src/main/java/opennlp/summarization/Sentence.java
summarizer/src/main/java/opennlp/summarization/lexicalchaining/NounPOSTagger.java
summarizer/src/main/java/opennlp/summarization/lexicalchaining/WordRelationshipDetermination.java
summarizer/src/main/java/opennlp/summarization/preprocess/DefaultDocProcessor.java

Change
-
- relates to OPENNLP-1729 and switches the Sandbox components to use SNAPSHOTS of OpenNLP core to benefit (and demonstrate) the new approach of loading models via jar files (available in the classpath).
- adapts code in `WSDHelper` to use ClassPathModelProvider
- adapts code in `ParserChunker2MatcherProcessor` to use ClassPathModelProvider
- adapts code in `NounPOSTagger` and `DefaultDocProcessor` to use ClassPathModelProvider
- removes redundant / duplicate code
- removes `commons-math3` dependency in `opennlp-similarity` component (lucky find)
- adds `@Override` where applicable
Notes
-
- `DownloadUtil` is not gone, as there is no _Chunker_ and no _Parser_ model provided as Maven artifact.
Tasks
-
In order to streamline the review …

OPENNLP-1729: Switch to easier loading of Models

---

opennlp-grpc/opennlp-grpc-service/src/main/java/opennlp/OpenNLPServer.java
opennlp-grpc/opennlp-grpc-service/src/test/resources/config-test.ini

Found that the standard maxInboundMessageSize needs to be configurable for bigger payloads.

OPENNLP-1737 - Allow configuration of the inbound message size

---

opennlp-coref/src/test/java/opennlp/tools/formats/muc/Muc6FullParseCorefSampleStreamFactoryTest.java
opennlp-grpc/opennlp-grpc-service/pom.xml
opennlp-grpc/opennlp-grpc-service/src/test/java/opennlp/OpenNLPServerIT.java
opennlp-grpc/opennlp-grpc-service/src/test/java/opennlp/service/AbstractServiceTest.java
opennlp-grpc/opennlp-grpc-service/src/test/java/opennlp/service/PosTaggerServiceTest.java
opennlp-grpc/opennlp-grpc-service/src/test/java/opennlp/service/SentenceDetectorServiceTest.java
opennlp-grpc/opennlp-grpc-service/src/test/java/opennlp/service/TokenizerServiceTest.java
pom.xml

Change
-
- adjusts version strings
Tasks
-

OPENNLP-1753: Switch to pre-trained Model binaries v1.3

---

caseditor-opennlp-plugin/src/main/java/org/apache/opennlp/caseditor/sentdetect/SentenceDetectorJob.java

Sanitize deprecation of SentenceDetectorME#getSentenceProbabilities()

---

caseditor-corpus-server-plugin/pom.xml
caseditor-opennlp-plugin/pom.xml
corpus-server/corpus-server-connector/pom.xml
corpus-server/corpus-server-core/pom.xml
corpus-server/corpus-server-impl/pom.xml
corpus-server/corpus-server-tools/pom.xml
corpus-server/pom.xml
mahout-addon/pom.xml
mallet-addon/pom.xml
modelbuilder-addon/pom.xml
nlp-utils/pom.xml
opennlp-brat-annotator/pom.xml
opennlp-coref/pom.xml
opennlp-dl/pom.xml
opennlp-grpc/README.md
opennlp-grpc/opennlp-grpc-api/pom.xml
opennlp-grpc/opennlp-grpc-service/pom.xml
opennlp-grpc/opennlp-grpc-service/src/main/java/opennlp/OpenNLPServer.java
opennlp-grpc/pom.xml
opennlp-similarity/pom.xml
opennlp-wsd/pom.xml
pom.xml
summarizer/pom.xml
tagging-server/pom.xml
tf-ner-poc/pom.xml
wikinews-importer/pom.xml

Change
-
- updates sandbox components to use opennlp-tools 2.5.5
- bumps snapshot version for next dev iteration
Tasks
-

Update to OpenNLP tools 2.5.5
